"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Building2, Search } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

import { PageHeader } from "@/components/data-display/page-header";
import { ContentSkeleton, EmptyState, ErrorState } from "@/components/feedback/query-state";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { adminApi } from "@/lib/api/endpoints/admin";
import { isApiError } from "@/lib/api/api-error";
import { formatDate, formatRupiah } from "@/lib/format";

export function CompaniesAdmin(){const client=useQueryClient();const [search,setSearch]=useState("");const query=useQuery({queryKey:["admin-companies",search],queryFn:()=>adminApi.companies(search)});const update=useMutation({mutationFn:({id,status}:{id:string;status:"active"|"inactive"})=>adminApi.updateCompany(id,{status}),onSuccess:()=>{toast.success("Status perusahaan diperbarui.");client.invalidateQueries({queryKey:["admin-companies"]});},onError:e=>toast.error(isApiError(e)?e.message:"Perubahan gagal.")});return <div className="space-y-6"><PageHeader eyebrow="Platform" title="Companies" description="Pantau dan kendalikan akses tenant. Menonaktifkan perusahaan tidak menghapus data."/><div className="relative max-w-md"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input className="pl-9" placeholder="Cari perusahaan…" value={search} onChange={e=>setSearch(e.target.value)}/></div>{query.isLoading?<ContentSkeleton/>:query.error?<ErrorState error={query.error} retry={()=>query.refetch()}/>:!query.data?.length?<EmptyState/>:<Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b bg-secondary/60 text-xs uppercase text-muted-foreground"><tr><th className="px-5 py-3">Perusahaan</th><th className="px-5 py-3">User</th><th className="px-5 py-3">Subscription</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Aksi</th></tr></thead><tbody className="divide-y">{query.data.map(item=><tr key={item.id}><td className="px-5 py-4"><p className="flex items-center gap-2 font-semibold"><Building2 className="size-4 text-primary"/>{item.name}</p><p className="mt-1 text-xs text-muted-foreground">{item.slug} · {item.timezone}</p></td><td className="px-5 py-4 tabular-nums">{item.users_count??0}</td><td className="px-5 py-4"><Badge variant={item.subscription?.status==="active"||item.subscription?.status==="trialing"?"success":"warning"}>{item.subscription?.status??"none"}</Badge></td><td className="px-5 py-4"><Badge variant={item.status==="active"?"success":"destructive"}>{item.status}</Badge></td><td className="px-5 py-4 text-right"><Button size="sm" variant="outline" disabled={update.isPending} onClick={()=>update.mutate({id:item.id,status:item.status==="active"?"inactive":"active"})}>{item.status==="active"?"Nonaktifkan":"Aktifkan"}</Button></td></tr>)}</tbody></table></div></Card>}</div>}

export function SubscriptionsAdmin(){const [status,setStatus]=useState("");const query=useQuery({queryKey:["admin-subscriptions",status],queryFn:()=>adminApi.subscriptions(status)});return <div className="space-y-6"><PageHeader eyebrow="Platform" title="Subscriptions" description="Daftar status langganan terbaru setiap tenant." action={<Select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Semua status</option><option value="trialing">Trialing</option><option value="active">Active</option><option value="past_due">Past due</option><option value="expired">Expired</option><option value="cancelled">Cancelled</option></Select>}/>{query.isLoading?<ContentSkeleton/>:query.error?<ErrorState error={query.error} retry={()=>query.refetch()}/>:!query.data?.length?<EmptyState/>:<Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b bg-secondary/60 text-xs uppercase text-muted-foreground"><tr><th className="px-5 py-3">Company</th><th className="px-5 py-3">Paket</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Trial berakhir</th><th className="px-5 py-3">Berakhir</th></tr></thead><tbody className="divide-y">{query.data.map(item=><tr key={item.id}><td className="px-5 py-4"><p className="font-semibold">{item.company.name}</p><p className="text-xs text-muted-foreground">{item.company.slug}</p></td><td className="px-5 py-4 uppercase">{item.plan_code}</td><td className="px-5 py-4"><Badge variant={item.can_mutate?"success":"warning"}>{item.status}</Badge></td><td className="px-5 py-4">{formatDate(item.trial_ends_at)}</td><td className="px-5 py-4">{formatDate(item.ends_at)}</td></tr>)}</tbody></table></div></Card>}</div>}

export function PaymentsAdmin(){const [status,setStatus]=useState("");const query=useQuery({queryKey:["admin-payments",status],queryFn:()=>adminApi.payments(status)});return <div className="space-y-6"><PageHeader eyebrow="Platform" title="Payments" description="Riwayat pembayaran yang benar-benar tercatat oleh sistem." action={<Select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Semua status</option><option value="pending">Pending</option><option value="paid">Paid</option><option value="failed">Failed</option><option value="refunded">Refunded</option></Select>}/>{query.isLoading?<ContentSkeleton/>:query.error?<ErrorState error={query.error} retry={()=>query.refetch()}/>:!query.data?.length?<EmptyState title="Belum ada pembayaran" description="Gateway pembayaran belum dikonfigurasi sehingga sistem tidak membuat transaksi palsu."/>:<Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b bg-secondary/60 text-xs uppercase text-muted-foreground"><tr><th className="px-5 py-3">Company</th><th className="px-5 py-3">Paket</th><th className="px-5 py-3 text-right">Jumlah</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Dibayar</th><th className="px-5 py-3">Referensi</th></tr></thead><tbody className="divide-y">{query.data.map(item=><tr key={item.id}><td className="px-5 py-4 font-semibold">{item.company?.name}</td><td className="px-5 py-4 uppercase">{item.subscription?.plan_code}</td><td className="px-5 py-4 text-right font-semibold">{formatRupiah(item.amount)}</td><td className="px-5 py-4"><Badge variant={item.status==="paid"?"success":item.status==="failed"?"destructive":"warning"}>{item.status}</Badge></td><td className="px-5 py-4">{formatDate(item.paid_at)}</td><td className="px-5 py-4 font-mono text-xs">{item.provider_reference??"—"}</td></tr>)}</tbody></table></div></Card>}</div>}
